# Generated by Django 5.2 on 2025-04-13 19:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDetail',
            fields=[
                ('client_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('client_name', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField()),
                ('address', models.TextField()),
                ('purchase_history', models.BigIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantDetail',
            fields=[
                ('merchant_code', models.BigIntegerField(primary_key=True, serialize=False)),
                ('merchant_name', models.CharField(max_length=100)),
                ('phone_number', models.BigIntegerField()),
                ('address', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('product_type', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('seller', models.CharField(max_length=100)),
                ('qr_code', models.ImageField(blank=True, upload_to='qr_codes/')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('category', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('category_stock', models.BigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CategoryN',
            fields=[
                ('category_n_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('weight', models.FloatField()),
                ('merchant_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.merchantdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Mortgage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField()),
                ('client_name', models.CharField(max_length=100)),
                ('product_category', models.CharField(max_length=100)),
                ('product_weight', models.FloatField()),
                ('product_actual_price', models.BigIntegerField()),
                ('product_price_kept', models.BigIntegerField()),
                ('duration', models.TimeField()),
                ('interest', models.FloatField()),
                ('start_date', models.DateField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.clientdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('category_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('category_type', models.BigIntegerField()),
                ('price', models.BigIntegerField()),
                ('weight', models.FloatField()),
                ('merchant_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.merchantdetail')),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
        ),
    ]
